A = float('{:0.1f}'.format(float(input())))
B = float('{:0.1f}'.format(float(input())))
C = float('{:0.1f}'.format(float(input())))
MEDIA = (((A * 2) + (B * 3) + (C * 5))/10)
print("MEDIA = " + '{:0.1f}'.format(MEDIA))